# Generated by Django 5.2.3 on 2025-08-14 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('road_name', models.CharField()),
                ('ward_number', models.CharField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('length_km', models.DecimalField(decimal_places=4, default=0.0, max_digits=200)),
                ('width_m', models.DecimalField(decimal_places=4, default=0.0, max_digits=200)),
                ('road_type', models.CharField(choices=[('IV', 'Road Type IV'), ('VI', 'Road Type VI'), ('others', 'Other Road Type')], default='IV')),
                ('material_type', models.CharField(choices=[('CC', 'Material Type CC'), ('IPB', 'Material Type IPB'), ('Bitumin', 'Material Type Bitumin'), ('Other', 'Other')], default='CC')),
                ('road_category', models.CharField(choices=[('ColonyStreet', 'Colony Street'), ('Road', 'Road'), ('Other', 'Other')], default='Road')),
                ('area_name', models.CharField(blank=True, default='Gumanpura', null=True)),
                ('district', models.CharField(blank=True, default='Kota', null=True)),
                ('state', models.CharField(blank=True, default='Rajasthan', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfraWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('progress_percent', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('completedOrpending', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('defect_liability_period', models.IntegerField(blank=True, default=0, help_text='Defect Liability Period in months', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='infra_images/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contractor')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.road')),
            ],
        ),
        migrations.CreateModel(
            name='OtherDepartmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('work_description', models.TextField()),
                ('requested_by', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('response_by', models.CharField(blank=True, max_length=255, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.road')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(auto_now_add=True)),
                ('status_note', models.TextField()),
                ('progress_percent', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='infra_images/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.infrawork')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('infra_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.infrawork')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.update')),
            ],
        ),
    ]
