# Generated by Django 5.2.3 on 2025-06-28 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=500, unique=True)),
                ('road_name', models.CharField()),
                ('ward_number', models.CharField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('length_km', models.DecimalField(decimal_places=4, default=0.0, max_digits=200)),
                ('width_m', models.DecimalField(decimal_places=4, default=0.0, max_digits=200)),
                ('road_type', models.CharField(choices=[('IV', 'Road Type IV'), ('VI', 'Road Type VI')], default='IV')),
                ('material_type', models.CharField(choices=[('CC', 'Material Type CC'), ('IPB', 'Material Type IPB'), ('Bitumin', 'Material Type Bitumin'), ('Other', 'Other')], default='CC')),
                ('road_category', models.CharField(choices=[('ColonyStreet', 'Colony Street'), ('Road', 'Road')], default='Road')),
            ],
        ),
        migrations.CreateModel(
            name='InfraWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('progress_percent', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('completedOrpending', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contractor')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.road')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(auto_now_add=True)),
                ('status_note', models.TextField()),
                ('progress_percent', models.IntegerField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.infrawork')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('commenter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('infra_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.infrawork')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.update')),
            ],
        ),
    ]
