# Generated by Django 5.2.3 on 2025-06-28 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='infrawork',
            name='vendor',
        ),
        migrations.AddField(
            model_name='road',
            name='material_type',
            field=models.CharField(choices=[('CC', 'Material Type CC'), ('IPB', 'Material Type IPB'), ('Bitumin', 'Material Type Bitumin'), ('Other', 'Other')], default='CC'),
        ),
        migrations.AddField(
            model_name='road',
            name='roadType',
            field=models.CharField(choices=[('ColonyStreet', 'Colony Street'), ('Road', 'Road')], default='Road'),
        ),
        migrations.AddField(
            model_name='road',
            name='road_type',
            field=models.CharField(choices=[('ColonyStreet', 'Colony Street'), ('Road', 'Road')], default='IV'),
        ),
        migrations.AddField(
            model_name='road',
            name='width_m',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='infrawork',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='road',
            name='length_km',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='road',
            name='unique_code',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='ward_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infrawork',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contractor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
