# Generated by Django 5.2.3 on 2025-08-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comments_deleteby_comments_deleteflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='deleteFlag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
