# Generated by Django 5.2.3 on 2025-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_road_road_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrawork',
            name='defect_liability_period',
            field=models.IntegerField(blank=True, default=0, help_text='Defect Liability Period in months', null=True),
        ),
    ]
