# Generated by Django 5.2.3 on 2025-06-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contractor_remove_infrawork_vendor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='road',
            old_name='roadType',
            new_name='road_category',
        ),
        migrations.AlterField(
            model_name='road',
            name='road_type',
            field=models.CharField(choices=[('IV', 'Road Type IV'), ('VI', 'Road Type VI')], default='IV'),
        ),
    ]
