# Generated by Django 5.2.3 on 2025-07-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_infrawork_defect_liability_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commenter_name',
            new_name='commenter',
        ),
        migrations.AddField(
            model_name='comments',
            name='ResponsiblePerson',
            field=models.CharField(blank=True, choices=[('JE', 'Junior Engineer'), ('AE', 'Assistant Engineer'), ('XEN', 'Executive Engineer'), ('SE', 'Superintending Engineer'), ('CE', 'Chief Engineer'), ('JCMC', 'Joint Commissioner'), ('CMC', 'Commissioner')], max_length=100, null=True),
        ),
    ]
