# Generated by Django 5.2.3 on 2025-08-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_infrawork_progress_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='infrawork',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='otherdepartmentrequest',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
