# Generated by Django 5.2.3 on 2025-07-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_commenter_name_comments_commenter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='ResponsiblePerson',
        ),
    ]
