# Generated by Django 5.2.3 on 2025-07-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_comments_responsibleperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
