# Generated by Django 5.2.3 on 2025-08-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comments_isactive_contractor_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrawork',
            name='pdfDescription',
            field=models.FileField(blank=True, null=True, upload_to='infra_pdfs/'),
        ),
        migrations.AddField(
            model_name='update',
            name='pdfDescription',
            field=models.FileField(blank=True, null=True, upload_to='infra_pdfs/'),
        ),
    ]
