# Generated by Django 5.2.3 on 2025-08-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_infrawork_pdfdescription_update_pdfdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdepartmentrequest',
            name='pdfDescription',
            field=models.FileField(blank=True, null=True, upload_to='other_department_pdfs/'),
        ),
    ]
