# Generated by Django 5.2.3 on 2025-09-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_otherdepartmentrequest_pdfdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrawork',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='infrawork',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
    ]
