# Generated by Django 5.2.3 on 2025-07-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_otherdepartmentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdepartmentrequest',
            name='contact_mobile',
        ),
    ]
