# Generated by Django 5.2.3 on 2025-07-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_otherdepartmentrequest_contact_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherdepartmentrequest',
            old_name='contact_email',
            new_name='contact_info',
        ),
    ]
