# Generated by Django 5.2.3 on 2025-09-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_infrawork_latitude_alter_infrawork_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
