# Generated by Django 5.2.3 on 2025-09-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_update_latitude_alter_update_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='material_type',
            field=models.CharField(choices=[('CC', 'Material Type CC'), ('KACCHA', 'Material Type KACCHA'), ('METALIC', 'Material Type METALIC'), ('Paver Block', 'Material Type Paver Block'), ('Other', 'Other')], default='Other'),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_category',
            field=models.CharField(choices=[('City Road', 'City Road'), ('Major District Road', 'Major District Road'), ('National Highway', 'National Highway'), ('State Highway', 'State Highway'), ('Other', 'Other')], default='Other'),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_type',
            field=models.CharField(choices=[('1', 'Road Type 1'), ('2', 'Road Type 2'), ('3', 'Road Type 3'), ('4', 'Road Type 4'), ('5', 'Road Type 5'), ('6', 'Road Type 6'), ('7', 'Road Type 7'), ('8', 'Road Type 8'), ('9', 'Road Type 9'), ('10', 'Road Type 10'), ('others', 'Other Road Type')], default='others'),
        ),
    ]
