# Generated by Django 5.2.3 on 2025-07-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_contact_email_otherdepartmentrequest_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdepartmentrequest',
            name='response',
        ),
    ]
