# Generated by Django 5.2.3 on 2025-09-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_road_material_type_alter_road_road_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='unique_code',
            field=models.CharField(blank=True, max_length=5000, null=True, unique=True),
        ),
    ]
