# Generated by Django 5.2.3 on 2025-09-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_road_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='material_type',
            field=models.CharField(default='Other'),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_category',
            field=models.CharField(default='Other'),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_type',
            field=models.CharField(default='others'),
        ),
    ]
