# Generated by Django 5.2.3 on 2025-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_otherdepartmentrequest_response_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdepartmentrequest',
            name='response_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
