# Generated by Django 5.2.3 on 2025-07-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_otherdepartmentrequest_response_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='area_name',
            field=models.CharField(blank=True, default='Gumanpura', null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='district',
            field=models.CharField(blank=True, default='Kota', null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='state',
            field=models.CharField(blank=True, default='Rajasthan', null=True),
        ),
    ]
