# Generated by Django 5.2.3 on 2025-07-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_road_area_name_road_district_road_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='road_category',
            field=models.CharField(choices=[('ColonyStreet', 'Colony Street'), ('Road', 'Road'), ('Other', 'Other')], default='Road'),
        ),
    ]
