# Generated by Django 5.2.3 on 2025-07-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_road_road_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrawork',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='unique_code',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
