# Generated by Django 5.2.3 on 2025-08-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_infrawork_end_date_alter_road_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrawork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='infra_images/'),
        ),
        migrations.AddField(
            model_name='infrawork',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='infrawork',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='infra_images/'),
        ),
        migrations.AddField(
            model_name='update',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
