# Generated by Django 5.2.3 on 2025-07-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('JE', 'Junior Engineer'), ('AE', 'Assistant Engineer'), ('XEN', 'Executive Engineer'), ('SE', 'Superintending Engineer'), ('CE', 'Chief Engineer'), ('JCMC', 'Joint Commissioner'), ('CMC', 'Commissioner')], default='other', max_length=20),
        ),
    ]
