# Generated by Django 5.2.3 on 2025-08-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditlog',
            name='new_details_of_affected_user',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='old_details_of_affected_user',
            field=models.TextField(),
        ),
    ]
