# Generated by Django 5.2.3 on 2025-08-13 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_userauditlog_delete_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauditlog',
            name='affected_user',
        ),
        migrations.RemoveField(
            model_name='userauditlog',
            name='details_snapshot',
        ),
        migrations.AddField(
            model_name='userauditlog',
            name='new_details_of_affected_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userauditlog',
            name='old_details_of_affected_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
